version: '3'
services:

  server:
    build:
      context: ./server
    ports:
      - "50051:50051"
    networks:
      - grpc-net

  client:
    build:
      context: ./client
    networks:
      - grpc-net
    depends_on:
      - server
      
networks:
  grpc-net:
    driver: bridge