version: '3'
services:

  server:
    build:
      context: .
      dockerfile: server.Dockerfile
    ports:
      - "50051:50051"
    networks:
      - grpc-net

  client:
    build:
      context: .
      dockerfile: client.Dockerfile
    networks:
      - grpc-net
    depends_on:
      - server
      
networks:
  grpc-net:
    driver: bridge